"""add price to spools.

Revision ID: d07d9e825564
Revises: 92793c8a937c
Create Date: 2023-09-23 14:31:13.012031
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d07d9e825564"
down_revision = "92793c8a937c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spool", sa.Column("price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spool", "price")
    # ### end Alembic commands ###
